stages:
  - build
  - deploy
  - prod

default:
  tags:
    - dff

.validate-template:
  image: node:20-bookworm-slim
  stage: build
  script:
    - export VITE_SERVER_URL=$VITE_SERVER_URL
    - export VITE_SUPPORT_PHONE=$VITE_SUPPORT_PHONE
    - export VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
    - npm install
    - yarn tsc
    # - yarn lint

.prod-template:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(?:[0-9]+)(?:\.[0-9]+){2}$/'

.deploy-template:
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY: dffreg.eridanus.ir
    DOCKER_IMAGE_TAG: latest
    DOCKER_REGISTRY_IMAGE: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: deploy
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE || true
    - docker build --build-arg VITE_SERVER_URL=$VITE_SERVER_URL --build-arg VITE_SUPPORT_PHONE=$VITE_SUPPORT_PHONE --build-arg VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL --cache-from $DOCKER_REGISTRY_IMAGE -t $DOCKER_REGISTRY_IMAGE .
    - docker push $DOCKER_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ------------------------------------ validate and build ------------------------------------

validate-stage:
  extends: .validate-template
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: staging
    action: prepare

validate-prod:
  extends:
    - .validate-template
    - .prod-template
  environment:
    name: production
    action: prepare

# ------------------------------------------ deploy ------------------------------------------

deploy:
  extends: .deploy-template
  environment:
    name: staging

productionize:
  extends:
    - .deploy-template
    - .prod-template
  stage: prod
  script:
    - NEW_DOCKER_IMAGE_TAG=$(echo $CI_COMMIT_TAG | sed -E 's/^(v[0-9]+).*/\1/')
    - if [ $MANUAL_DOCKER_IMAGE_TAG ]; then NEW_DOCKER_IMAGE_TAG=$MANUAL_DOCKER_IMAGE_TAG; fi
    - DOCKER_REGISTRY_IMAGE=$(echo $DOCKER_REGISTRY_IMAGE | sed "s/:${DOCKER_IMAGE_TAG}/:${NEW_DOCKER_IMAGE_TAG}/")
    - !reference [.deploy-template, script]
  when: manual
  environment:
    name: production
