/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApartmentDetails
 */
export interface ApartmentDetails {
    /**
     * 
     * @type {number}
     * @memberof ApartmentDetails
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentDetails
     */
    'units_per_floor_number': number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentDetails
     */
    'file_record': number;
}

