/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BuildingDetailsRequest
 */
export interface BuildingDetailsRequest {
    /**
     * 
     * @type {number}
     * @memberof BuildingDetailsRequest
     */
    'construction_year': number;
    /**
     * 
     * @type {number}
     * @memberof BuildingDetailsRequest
     */
    'floors_count': number;
}

