/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `APARTMENT` - آپارتمان * `HOUSE` - خانه/ویلا * `LAND` - زمین * `COMMERCIAL` - اداری/تجاری
 * @export
 * @enum {string}
 */

export const EstateTypeEnum = {
    Apartment: 'APARTMENT',
    House: 'HOUSE',
    Land: 'LAND',
    Commercial: 'COMMERCIAL'
} as const;

export type EstateTypeEnum = typeof EstateTypeEnum[keyof typeof EstateTypeEnum];



