/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `DIVAR` - دیوار * `DAFTAR_FILE` - دفتر فایل
 * @export
 * @enum {string}
 */

export const FileSourceEnum = {
    Divar: 'DIVAR',
    DaftarFile: 'DAFTAR_FILE'
} as const;

export type FileSourceEnum = typeof FileSourceEnum[keyof typeof FileSourceEnum];



