/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginOtpRequest
 */
export interface LoginOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginOtpRequest
     */
    'mobile_number': string;
}

