/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `FILE_COMPLETED` - فایل تکمیل شده * `OWNER_NOT_RESPONSIBLE` - مالک پاسخگو نبود * `OWNER_NOT_COOPERATE` - مالک همکاری نکرد
 * @export
 * @enum {string}
 */

export const OwnerStatusEnum = {
    FileCompleted: 'FILE_COMPLETED',
    OwnerNotResponsible: 'OWNER_NOT_RESPONSIBLE',
    OwnerNotCooperate: 'OWNER_NOT_COOPERATE'
} as const;

export type OwnerStatusEnum = typeof OwnerStatusEnum[keyof typeof OwnerStatusEnum];



