/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileRecordList } from './file-record-list';

/**
 * 
 * @export
 * @interface PaginatedFileRecordListList
 */
export interface PaginatedFileRecordListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileRecordListList
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileRecordListList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileRecordListList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<FileRecordList>}
     * @memberof PaginatedFileRecordListList
     */
    'results': Array<FileRecordList>;
}

