/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApartmentDetailsRequest } from './apartment-details-request';
// May contain unused imports in some cases
// @ts-ignore
import type { ApartmentUnitDetailsRequest } from './apartment-unit-details-request';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildingDetailsRequest } from './building-details-request';
// May contain unused imports in some cases
// @ts-ignore
import type { BuySellPriceRequest } from './buy-sell-price-request';
// May contain unused imports in some cases
// @ts-ignore
import type { EstateDirectionEnum } from './estate-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { EstateTypeEnum } from './estate-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { FileSourceEnum } from './file-source-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { LandDetailsRequest } from './land-details-request';
// May contain unused imports in some cases
// @ts-ignore
import type { OwnerStatusEnum } from './owner-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RentCreditPriceRequest } from './rent-credit-price-request';
// May contain unused imports in some cases
// @ts-ignore
import type { TradeTypeEnum } from './trade-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { UnitBaseRequest } from './unit-base-request';

/**
 * 
 * @export
 * @interface PatchedFileRecordRequest
 */
export interface PatchedFileRecordRequest {
    /**
     * 
     * @type {BuildingDetailsRequest}
     * @memberof PatchedFileRecordRequest
     */
    'building_details'?: BuildingDetailsRequest;
    /**
     * 
     * @type {UnitBaseRequest}
     * @memberof PatchedFileRecordRequest
     */
    'unit_base'?: UnitBaseRequest;
    /**
     * 
     * @type {ApartmentDetailsRequest}
     * @memberof PatchedFileRecordRequest
     */
    'apartment_details'?: ApartmentDetailsRequest;
    /**
     * 
     * @type {ApartmentUnitDetailsRequest}
     * @memberof PatchedFileRecordRequest
     */
    'apartment_unit_details'?: ApartmentUnitDetailsRequest;
    /**
     * 
     * @type {LandDetailsRequest}
     * @memberof PatchedFileRecordRequest
     */
    'land_details'?: LandDetailsRequest;
    /**
     * 
     * @type {RentCreditPriceRequest}
     * @memberof PatchedFileRecordRequest
     */
    'rent_credit_price'?: RentCreditPriceRequest;
    /**
     * 
     * @type {BuySellPriceRequest}
     * @memberof PatchedFileRecordRequest
     */
    'buy_sell_price'?: BuySellPriceRequest;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedFileRecordRequest
     */
    'estate_owner_phones'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedFileRecordRequest
     */
    'file_title'?: string;
    /**
     * 
     * @type {FileSourceEnum}
     * @memberof PatchedFileRecordRequest
     */
    'file_source'?: FileSourceEnum;
    /**
     * 
     * @type {EstateTypeEnum}
     * @memberof PatchedFileRecordRequest
     */
    'estate_type'?: EstateTypeEnum;
    /**
     * 
     * @type {TradeTypeEnum}
     * @memberof PatchedFileRecordRequest
     */
    'trade_type'?: TradeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedFileRecordRequest
     */
    'address'?: string;
    /**
     * 
     * @type {EstateDirectionEnum}
     * @memberof PatchedFileRecordRequest
     */
    'estate_direction'?: EstateDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedFileRecordRequest
     */
    'estate_owner_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedFileRecordRequest
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedFileRecordRequest
     */
    'has_document'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedFileRecordRequest
     */
    'has_termination'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedFileRecordRequest
     */
    'has_license'?: boolean;
    /**
     * 
     * @type {OwnerStatusEnum}
     * @memberof PatchedFileRecordRequest
     */
    'owner_status'?: OwnerStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedFileRecordRequest
     */
    'district'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedFileRecordRequest
     */
    'main_image'?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedFileRecordRequest
     */
    'estate_tags'?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedFileRecordRequest
     */
    'images'?: Array<number>;
}



