/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RentCreditPriceRequest
 */
export interface RentCreditPriceRequest {
    /**
     * 
     * @type {number}
     * @memberof RentCreditPriceRequest
     */
    'rent': number;
    /**
     * 
     * @type {number}
     * @memberof RentCreditPriceRequest
     */
    'mortgage': number;
}

