/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `GOD` - خدا * `OPERATOR` - اپراتور * `AGENT` - مشاور * `SUPPORTER` - ناظر
 * @export
 * @enum {string}
 */

export const RoleNameEnum = {
    God: 'GOD',
    Operator: 'OPERATOR',
    Agent: 'AGENT',
    Supporter: 'SUPPORTER'
} as const;

export type RoleNameEnum = typeof RoleNameEnum[keyof typeof RoleNameEnum];



