/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `BUY_SELL` - خرید و فروش * `RENT_CREDIT` -  رهن و اجاره
 * @export
 * @enum {string}
 */

export const TradeTypeEnum = {
    BuySell: 'BUY_SELL',
    RentCredit: 'RENT_CREDIT'
} as const;

export type TradeTypeEnum = typeof TradeTypeEnum[keyof typeof TradeTypeEnum];



