/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UnitBaseRequest
 */
export interface UnitBaseRequest {
    /**
     * 
     * @type {number}
     * @memberof UnitBaseRequest
     */
    'rooms_count': number;
    /**
     * 
     * @type {number}
     * @memberof UnitBaseRequest
     */
    'toilets_count': number;
    /**
     * 
     * @type {number}
     * @memberof UnitBaseRequest
     */
    'parkings_count': number;
    /**
     * 
     * @type {boolean}
     * @memberof UnitBaseRequest
     */
    'has_elevator': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UnitBaseRequest
     */
    'has_warehouse': boolean;
    /**
     * 
     * @type {number}
     * @memberof UnitBaseRequest
     */
    'unit_meterage': number;
}

