/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `NORTHERN` - شمالی * `SOUTHERN` - جنوبی * `EASTERN` - شرقی * `WESTERN` - غربی * `DOUBLE_CORNERS` - دو نبشه * `MIDDLE` - میانی
 * @export
 * @enum {string}
 */

export const UnitDirectionEnum = {
    Northern: 'NORTHERN',
    Southern: 'SOUTHERN',
    Eastern: 'EASTERN',
    Western: 'WESTERN',
    DoubleCorners: 'DOUBLE_CORNERS',
    Middle: 'MIDDLE'
} as const;

export type UnitDirectionEnum = typeof UnitDirectionEnum[keyof typeof UnitDirectionEnum];



