/* tslint:disable */
/* eslint-disable */
/**
 * Daftar File Project API
 * API List of Dafter-File Project
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoleNameEnum } from './role-name-enum';

/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'mobile_number': string;
    /**
     * 
     * @type {RoleNameEnum}
     * @memberof UserInfo
     */
    'role_name': RoleNameEnum;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'full_name': string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'company_name': string;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    'remaining_subscription_days': number;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    'subscription_days': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserInfo
     */
    'cities_access': Array<string>;
}



